logo
codervivek5/VigyBag pull request #1097
Opened 2024-05-18 17:27 UTC by solanki505

## Fixes Issue #1067

2024-05-19 18:14 UTC, codervivek5 requested changes
try to make these changes then send me sample plz

2024-05-19 18:14 UTC, codervivek5 commented on Screenshot_2024-05-18_174852-removebg-preview.png
can you add a background color only in circle use light color and make VigyBag bold and not seperate it also

2024-05-19 18:16 UTC, solanki505 commented on Screenshot_2024-05-18_174852-removebg-preview.png
ok I will make this changes

2024-05-19 18:17 UTC, codervivek5 commented on Screenshot_2024-05-18_174852-removebg-preview.png
sure

2024-05-19 19:00 UTC, codervivek5 requested changes

2024-05-19 19:00 UTC, codervivek5 commented on Screenshot_2024-05-18_183654-removebg-preview.png
make a copy of above design same like this also

2024-05-19 19:00 UTC, codervivek5 commented on New Project1.png
@solanki505 border is looking osm. can you add it in all side ?

2024-05-19 19:01 UTC, solanki505 commented on New Project1.png
> @solanki505 border is looking osm. can you add it in all side ?

okay

2024-05-20 09:18 UTC, solanki505 commented on Screenshot_2024-05-18_183654-removebg-preview.png
done

2024-05-20 09:21 UTC, solanki505 commented on Screenshot_2024-05-18_183654-removebg-preview.png
@codervivek5  please suggest if further changes are required, if the changes are okay please assign the task to me.

2024-05-20 16:27 UTC, codervivek5 commented
kindly solve the merge conflit

2024-05-20 17:01 UTC, solanki505 commented
@codervivek5 

ok sir

2024-05-23 10:37 UTC, solanki505 commented
Sir does the changes are okay or it need further changes please suggest

2024-05-27 05:11 UTC, codervivek5 commented
make sure your all logos are separate in the root folder with name  "New Logo"

2024-05-27 07:25 UTC, solanki505 commented
> make sure your all logos are separate in the root folder with name "New Logo"

okay

2024-05-28 02:58 UTC, codervivek5 commented
Have you done this ?

2024-05-28 03:25 UTC, solanki505 commented
> Have you done this ?

Yes I separated it in folder new logo.

2024-06-03 06:04 UTC, closed without merging