Development- auth
codervivek5/VigyBag pull request #246
Opened 2023-05-26 08:17 UTC by sanya-mahajan

#34

2023-05-26 16:13 UTC, codervivek5 commented
@sanya-mahajan can I see your changes so that I can review

2023-05-26 18:01 UTC, sanya-mahajan commented
![Screenshot from 2023-05-26 23-30-24](https://github.com/codervivek5/VigyBag/assets/88281057/a8f77c29-028b-44a8-bc87-7922480eb921)
![Screenshot from 2023-05-26 23-30-14](https://github.com/codervivek5/VigyBag/assets/88281057/8e5e9fd7-6f1c-4e0b-933c-069a56845886)

2023-05-26 19:17 UTC, JigarJoshi04 requested changes

2023-05-26 19:17 UTC, JigarJoshi04 commented on Backend Code/VigyBag/users/views.py
> +            print(1)
I think this is a redundant print and can be removed

2023-05-26 19:17 UTC, JigarJoshi04 commented on Backend Code/VigyBag/users/views.py
> +            return Response({'status':'failed','message':'Email already exists'},status=status.HTTP_400_BAD_REQUEST)
I think this check should happen after the serialising step

2023-05-26 19:17 UTC, JigarJoshi04 commented on Backend Code/VigyBag/users/serializers.py
> +        return user
This is a Create operation (An operation that should ideally be performed by repository of the code). It should not be placed in the serializer file. 

Serializers allow complex data such as querysets and model instances to be converted to native Python datatypes that can then be easily rendered into JSON, XML or other content types. Serializers also provide deserialization, allowing parsed data to be converted back into complex types, after first validating the incoming data.

Ref: https://www.django-rest-framework.org/api-guide/serializers/

2023-05-26 19:17 UTC, JigarJoshi04 commented on Backend Code/VigyBag/users/serializers.py
> +            print(1234)
Redundant print statement that can be removed.

2023-05-26 19:17 UTC, JigarJoshi04 commented on Backend Code/VigyBag/users/serializers.py
> +            user=authenticate(email=email, password=password)
This is again a call to function of the buisness logic layer that serializer should not be making.
Suggesting to move business logic and triggers to business logic out of serializers.

2023-05-27 00:37 UTC, sanya-mahajan commented
Thank you for the feedback, would be working on it

2023-05-27 01:29 UTC, sanya-mahajan commented
@JigarJoshi04 sir, kindly review the updates

2023-06-16 18:50 UTC, codervivek5 approved these changes

2023-06-22 18:02 UTC, merged